version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - /var/www/vendor
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lowyer
    volumes:
      - dbdata:/var/lib/mysql
    networks:
    - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge